modulo1/git/sobre-mim/comidas.txt
=> Comidas-Favoritas

modulo1/git/sobre-mim/filmes.txt
=> Filmes-Favoritos

modulo1/git/sobre-mim/musicas.txt
=> Músicas-Favoritas

modulo1/strings-arrays/index.html, modulo1/strings-arrays/index.js
=> arraysEstrings

modulo1/objetos/index.html, modulo1/objetos/index.js
=> Exercicio-de-objetos

modulo1/projeto-blackjack/desafio.js, modulo1/projeto-blackjack/index.html, modulo1/projeto-blackjack/naoMexer.js, modulo1/projeto-blackjack/nossoJogo.js
=> Projeto-de-Fixaca-Black-Jack

modulo4/sistema-banco/.gitignore, modulo4/sistema-banco/package-lock.json, modulo4/sistema-banco/package.json, modulo4/sistema-banco/src/data.ts, modulo4/sistema-banco/src/index.ts, modulo4/sistema-banco/tsconfig.json
https://documenter.getpostman.com/view/20349301/Uz5Gnw2n
=> sistema-bancário

modulo4/node-package-json/.gitignore, modulo4/node-package-json/Exercicio1/index.js, modulo4/node-package-json/Exercicio1/package.json, modulo4/node-package-json/Exercicio2/index.js, modulo4/node-package-json/Exercicio2/package.json, modulo4/node-package-json/Exercicio3/index.js, modulo4/node-package-json/Exercicio3/package.json
=> Exercício de node package json

modulo4/intro-typescript/template-typescript/.gitignore, modulo4/intro-typescript/template-typescript/package-lock.json, modulo4/intro-typescript/template-typescript/package.json, modulo4/intro-typescript/template-typescript/src/Exercicio1.ts, modulo4/intro-typescript/template-typescript/src/Exercicio2.ts, modulo4/intro-typescript/template-typescript/src/Exercicio3.ts, modulo4/intro-typescript/template-typescript/src/Exercicio4.ts, modulo4/intro-typescript/template-typescript/src/Exercicio5.ts, modulo4/intro-typescript/template-typescript/tsconfig.json
=> intro-typescript

modulo4/aprofundamento-typescript/aprofundamento-typescript/.gitignore, modulo4/aprofundamento-typescript/aprofundamento-typescript/package-lock.json, modulo4/aprofundamento-typescript/aprofundamento-typescript/package.json, modulo4/aprofundamento-typescript/aprofundamento-typescript/src/Exercicio1.ts, modulo4/aprofundamento-typescript/aprofundamento-typescript/src/Exercicio2.ts, modulo4/aprofundamento-typescript/aprofundamento-typescript/src/Exercicio3.ts, modulo4/aprofundamento-typescript/aprofundamento-typescript/src/Exercicio4.ts, modulo4/aprofundamento-typescript/aprofundamento-typescript/src/Exercicio5.ts, modulo4/aprofundamento-typescript/aprofundamento-typescript/tsconfig.json
=> aprofundamento typescript

modulo4/aprofundamento-express/.gitignore, modulo4/aprofundamento-express/package-lock.json, modulo4/aprofundamento-express/package.json, modulo4/aprofundamento-express/src/index.ts, modulo4/aprofundamento-express/tsconfig.json, modulo4/fluxo-de-dados-backend/.gitignore, modulo4/fluxo-de-dados-backend/package-lock.json, modulo4/fluxo-de-dados-backend/package.json, modulo4/fluxo-de-dados-backend/src/data.ts, modulo4/fluxo-de-dados-backend/src/index.ts, modulo4/fluxo-de-dados-backend/tsconfig.json
Documentação: https://documenter.getpostman.com/view/20349301/Uz5DqdH8#ebc560f3-ff9a-459c-a574-0f7a01275070
=> Aprofundamento em express

modulo4/fluxo-de-dados-backend/.gitignore, modulo4/fluxo-de-dados-backend/package-lock.json, modulo4/fluxo-de-dados-backend/package.json, modulo4/fluxo-de-dados-backend/src/data.ts, modulo4/fluxo-de-dados-backend/src/index.ts, modulo4/fluxo-de-dados-backend/tsconfig.json
https://documenter.getpostman.com/view/20349301/Uz5FJc7g#0b6cda17-96c7-42e3-9a49-d19122f6ff57
=> Fluxo de dados

modulo4/introducao-sql/IntroducaoSQL.md
=> Introducao SQL

modulo4/aprofundamento-sql/aprofundamento-sql.md
=> Aprofundamento-SQL

modulo4/relacoes-sql/relacoes-sql.md
=> Relacoes SQL

modulo4/knex-js/Knex/.gitignore, modulo4/knex-js/Knex/TesteApi.rest, modulo4/knex-js/Knex/package-lock.json, modulo4/knex-js/Knex/package.json, modulo4/knex-js/Knex/src/app.ts, modulo4/knex-js/Knex/src/connection.ts, modulo4/knex-js/Knex/src/index.ts, modulo4/knex-js/Knex/tsconfig.json
=> knex-js exercicios

modulo4/async-await-promises/exercicios-async-await-promises/.gitignore, modulo4/async-await-promises/exercicios-async-await-promises/package-lock.json, modulo4/async-await-promises/exercicios-async-await-promises/package.json, modulo4/async-await-promises/exercicios-async-await-promises/src/baseURL.ts, modulo4/async-await-promises/exercicios-async-await-promises/src/ex1.ts, modulo4/async-await-promises/exercicios-async-await-promises/src/ex2.ts, modulo4/async-await-promises/exercicios-async-await-promises/src/ex3.ts, modulo4/async-await-promises/exercicios-async-await-promises/src/ex4.ts, modulo4/async-await-promises/exercicios-async-await-promises/src/ex5.ts, modulo4/async-await-promises/exercicios-async-await-promises/src/ex6.ts, modulo4/async-await-promises/exercicios-async-await-promises/tsconfig.json
=> Async-await-promises

modulo4/Projeto ToDoList WFS11-S16/.gitignore, modulo4/Projeto ToDoList WFS11-S16/package-lock.json, modulo4/Projeto ToDoList WFS11-S16/package.json, modulo4/Projeto ToDoList WFS11-S16/src/Endpoints/createTask.ts, modulo4/Projeto ToDoList WFS11-S16/src/Endpoints/createUsers.ts, modulo4/Projeto ToDoList WFS11-S16/src/Endpoints/deleteTask.ts, modulo4/Projeto ToDoList WFS11-S16/src/Endpoints/deleteUser.ts, modulo4/Projeto ToDoList WFS11-S16/src/Endpoints/getTaskById.ts, modulo4/Projeto ToDoList WFS11-S16/src/Endpoints/getUsers.ts, modulo4/Projeto ToDoList WFS11-S16/src/Endpoints/getUsersById.ts, modulo4/Projeto ToDoList WFS11-S16/src/Endpoints/updateUserById.ts, modulo4/Projeto ToDoList WFS11-S16/src/app.ts, modulo4/Projeto ToDoList WFS11-S16/src/connection.ts, modulo4/Projeto ToDoList WFS11-S16/src/index.ts, modulo4/Projeto ToDoList WFS11-S16/tsconfig.json
https://documenter.getpostman.com/view/20349301/Uz5NiXzX#54ad991f-134e-47db-bc60-c4ac19332ebd
=> ToDoList Projeto

modulo4/lista-typescript/lista-typescript/.gitignore, modulo4/lista-typescript/lista-typescript/package-lock.json, modulo4/lista-typescript/lista-typescript/package.json, modulo4/lista-typescript/lista-typescript/src/Exercicio1.ts, modulo4/lista-typescript/lista-typescript/src/Exercicio10.ts, modulo4/lista-typescript/lista-typescript/src/Exercicio11.ts, modulo4/lista-typescript/lista-typescript/src/Exercicio2.ts, modulo4/lista-typescript/lista-typescript/src/Exercicio3.ts, modulo4/lista-typescript/lista-typescript/src/Exercicio4.ts, modulo4/lista-typescript/lista-typescript/src/Exercicio5.ts, modulo4/lista-typescript/lista-typescript/src/Exercicio6.ts, modulo4/lista-typescript/lista-typescript/src/Exercicio7.ts, modulo4/lista-typescript/lista-typescript/src/Exercicio8.ts, modulo4/lista-typescript/lista-typescript/src/Exercicio9.ts, modulo4/lista-typescript/lista-typescript/tsconfig.json
=> lista-typescript

modulo5/criptografia-e-user-roles/.gitignore, modulo5/criptografia-e-user-roles/package-lock.json, modulo5/criptografia-e-user-roles/package.json, modulo5/criptografia-e-user-roles/src/app.ts, modulo5/criptografia-e-user-roles/src/data/BaseDatabase.ts, modulo5/criptografia-e-user-roles/src/data/UserDatabase.ts, modulo5/criptografia-e-user-roles/src/endpoints/createUser.ts, modulo5/criptografia-e-user-roles/src/endpoints/editUser.ts, modulo5/criptografia-e-user-roles/src/endpoints/getProfile.ts, modulo5/criptografia-e-user-roles/src/endpoints/login.ts, modulo5/criptografia-e-user-roles/src/index.ts, modulo5/criptografia-e-user-roles/src/services/Authenticator.ts, modulo5/criptografia-e-user-roles/src/services/Generate.ts, modulo5/criptografia-e-user-roles/src/types.ts, modulo5/criptografia-e-user-roles/tables.sql, modulo5/criptografia-e-user-roles/tsconfig.json
=> criptografia

modulo5/introducao-autenticacao/Respostas.md, modulo5/introducao-autenticacao/package-lock.json, modulo5/introducao-autenticacao/package.json, modulo5/introducao-autenticacao/requests.rest, modulo5/introducao-autenticacao/src/app.ts, modulo5/introducao-autenticacao/src/data/BaseDatabase.ts, modulo5/introducao-autenticacao/src/data/UserDatabase.ts, modulo5/introducao-autenticacao/src/endpoints/createUser.ts, modulo5/introducao-autenticacao/src/endpoints/editUser.ts, modulo5/introducao-autenticacao/src/index.ts, modulo5/introducao-autenticacao/src/services/GenerateId.ts, modulo5/introducao-autenticacao/src/services/GenerateToken.ts, modulo5/introducao-autenticacao/src/types.ts, modulo5/introducao-autenticacao/tables.sql, modulo5/introducao-autenticacao/tsconfig.json
=> introducao

modulo6/ProjetoAmaro/.gitignore, modulo6/ProjetoAmaro/README.md, modulo6/ProjetoAmaro/jest.config.js, modulo6/ProjetoAmaro/package-lock.json, modulo6/ProjetoAmaro/package.json, modulo6/ProjetoAmaro/src/Business/CreateProductsBusiness.ts, modulo6/ProjetoAmaro/src/Business/GetProductsByNameBusiness.ts, modulo6/ProjetoAmaro/src/Controller/CreateProductsController.ts, modulo6/ProjetoAmaro/src/Controller/GetProductsByNameController.ts, modulo6/ProjetoAmaro/src/Data/BaseDataBase.ts, modulo6/ProjetoAmaro/src/Data/ProductsDataBase.ts, modulo6/ProjetoAmaro/src/Models/InputCreateProducts.ts, modulo6/ProjetoAmaro/src/Services/IdGenerate.ts, modulo6/ProjetoAmaro/src/app.ts, modulo6/ProjetoAmaro/src/index.ts, modulo6/ProjetoAmaro/tsconfig.json
Projeto escolhido: https://github.com/amaroteam/back-end-challenge
Documentação da api: https://documenter.getpostman.com/view/20349301/UzXNSwbt
=> Projeto Case 2
